import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Bground from "@/components/home/background";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[url('../img/background.webp')] w-screen h-screen bg-cover bg-no-repeat">
          
        
        {children}
        </div>
      </body>
    </html>
  );
}
